//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVCApplicaiton
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITTABLE
    {
        public int LOGID { get; set; }
        public string TEXTData { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
