//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVCApplicaiton
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_20230603
    {
        public int User_Address_ID { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Expr1 { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Department { get; set; }
        public Nullable<int> ParentUserID { get; set; }
    }
}
